// lib/education/primary/primary_lesson_plan_sheet.dart
// ignore_for_file: deprecated_member_use
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'primary_ai_service.dart';

/// Teacher-only lesson plan generator bottom sheet.
/// Long-press any topic card on PrimaryHomeScreen → show this.
///
/// Usage:
///   showModalBottomSheet(
///     context: context,
///     isScrollControlled: true,
///     backgroundColor: Colors.transparent,
///     builder: (_) => DraggableScrollableSheet(
///       initialChildSize: 0.9,
///       builder: (_, sc) => PrimaryLessonPlanSheet(
///         topic: 'Farm Animals', grade: 'Grade 3'),
///     ),
///   );
class PrimaryLessonPlanSheet extends StatefulWidget {
  final String topic, grade;
  const PrimaryLessonPlanSheet({super.key, required this.topic, required this.grade});

  @override
  State<PrimaryLessonPlanSheet> createState() => _PrimaryLessonPlanSheetState();
}

class _PrimaryLessonPlanSheetState extends State<PrimaryLessonPlanSheet> {
  final _service = const PrimaryAiService();
  _LPState    _state = _LPState.loading;
  LessonPlan? _plan;

  @override
  void initState() { super.initState(); _load(); }

  Future<void> _load() async {
    setState(() => _state = _LPState.loading);
    final plan = await _service.generateLessonPlan(
        topic: widget.topic, grade: widget.grade);
    if (!mounted) return;
    setState(() { _plan = plan; _state = plan == null ? _LPState.error : _LPState.done; });
  }

  Future<void> _copyToClipboard() async {
    final p = _plan!;
    final text = '''
LESSON PLAN — ${p.topic}
Grade: ${widget.grade}

OBJECTIVE
${p.objective}

MATERIALS NEEDED
${p.materials}

ACTIVITY SEQUENCE
${p.activity}

ASSESSMENT QUESTIONS
${p.assessment}

Generated by Kilimomkononi Education AI
''';
    await Clipboard.setData(ClipboardData(text: text));
    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Lesson plan copied to clipboard!'),
            duration: Duration(seconds: 2)));
    }
  }

  @override
  Widget build(BuildContext context) {
    const c = Color(0xFF003900);
    return Container(
      decoration: const BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(24))),
      child: Column(children: [
        // Drag handle
        Center(child: Container(
            margin: const EdgeInsets.only(top: 12, bottom: 4), width: 36, height: 4,
            decoration: BoxDecoration(color: Colors.grey.shade300, borderRadius: BorderRadius.circular(2)))),
        // Header
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 8, 16, 0),
          child: Row(children: [
            Container(padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(color: const Color(0xFF003900).withOpacity(0.1),
                  borderRadius: BorderRadius.circular(10)),
              child: const Icon(Icons.menu_book_rounded, color: Color(0xFF003900), size: 20)),
            const SizedBox(width: 12),
            Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              const Text('Lesson Plan', style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold,
                  color: Color(0xFF003900))),
              Text('${widget.topic} · ${widget.grade}',
                  style: TextStyle(fontSize: 12, color: Colors.grey.shade500)),
            ])),
            if (_state == _LPState.done) ...[
              IconButton(icon: const Icon(Icons.copy_rounded, size: 20), color: c,
                  tooltip: 'Copy to clipboard', onPressed: _copyToClipboard),
              IconButton(icon: const Icon(Icons.refresh_rounded, size: 20),
                  color: Colors.grey.shade400, onPressed: _load),
            ],
            IconButton(icon: const Icon(Icons.close, size: 20), color: Colors.grey.shade400,
                onPressed: () => Navigator.pop(context)),
          ]),
        ),
        const Divider(height: 20, indent: 20, endIndent: 20),
        Expanded(child: switch (_state) {
          _LPState.loading => _buildLoading(),
          _LPState.error   => _buildError(),
          _LPState.done    => _buildPlan(),
        }),
      ]),
    );
  }

  Widget _buildLoading() => const Center(child: Column(mainAxisSize: MainAxisSize.min, children: [
    CircularProgressIndicator(color: Color(0xFF003900)),
    SizedBox(height: 16),
    Text('Writing your lesson plan…', style: TextStyle(fontSize: 13, color: Color(0xFF558B2F))),
  ]));

  Widget _buildError() => Center(child: Column(mainAxisSize: MainAxisSize.min, children: [
    Icon(Icons.wifi_off_rounded, size: 52, color: Colors.grey.shade300),
    const SizedBox(height: 12),
    Text('Could not generate. Check your connection.',
        textAlign: TextAlign.center, style: TextStyle(fontSize: 13, color: Colors.grey.shade600)),
    const SizedBox(height: 20),
    ElevatedButton.icon(onPressed: _load, icon: const Icon(Icons.refresh, size: 16),
        label: const Text('Try again'),
        style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF003900),
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)))),
  ]));

  Widget _buildPlan() {
    final p = _plan!;
    return ListView(padding: const EdgeInsets.fromLTRB(20, 0, 20, 32), children: [
      _Section(icon: Icons.flag_rounded, color: const Color(0xFF2E7D32),
          title: 'Learning objective', body: p.objective),
      _Section(icon: Icons.inventory_2_rounded, color: const Color(0xFF0277BD),
          title: 'Materials needed', body: p.materials),
      _Section(icon: Icons.format_list_numbered_rounded, color: const Color(0xFFE65100),
          title: 'Activity sequence', body: p.activity),
      _Section(icon: Icons.quiz_rounded, color: const Color(0xFF6A1B9A),
          title: 'End-of-lesson assessment', body: p.assessment),
      const SizedBox(height: 16),
      SizedBox(width: double.infinity,
        child: ElevatedButton.icon(
          onPressed: _copyToClipboard,
          icon: const Icon(Icons.copy_rounded, size: 16),
          label: const Text('Copy lesson plan'),
          style: ElevatedButton.styleFrom(
              backgroundColor: const Color(0xFF003900), foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(vertical: 14),
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
        )),
    ]);
  }
}

class _Section extends StatelessWidget {
  final IconData icon; final Color color; final String title, body;
  const _Section({required this.icon, required this.color, required this.title, required this.body});
  @override
  Widget build(BuildContext context) => Container(
    margin: const EdgeInsets.only(bottom: 14),
    padding: const EdgeInsets.all(14),
    decoration: BoxDecoration(
        color: color.withOpacity(0.05),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withOpacity(0.15))),
    child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        Icon(icon, color: color, size: 16),
        const SizedBox(width: 8),
        Text(title, style: TextStyle(fontSize: 12, fontWeight: FontWeight.bold, color: color)),
      ]),
      const SizedBox(height: 8),
      Text(body, style: const TextStyle(fontSize: 13.5, height: 1.6)),
    ]),
  );
}

enum _LPState { loading, error, done }