import 'package:cloud_firestore/cloud_firestore.dart';

class DiseaseData {
  final String name;
  final String imagePath;
  final List<String> preventionStrategies;
  final String activeAgent;
  final List<String> possibleCauses;
  final List<String> fungicides; 

  DiseaseData({
    required this.name,
    required this.imagePath,
    required this.preventionStrategies,
    required this.activeAgent,
    required this.possibleCauses,
    required this.fungicides,
  });

  static final Map<String, DiseaseData> diseaseLibrary = {
    // A
    'Alternaria Leaf Blight': DiseaseData(
      name: 'Alternaria Leaf Blight',
      imagePath: 'assets/diseases/alternaria_leaf_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid overhead irrigation'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Warm, wet conditions', 'Poor air circulation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Alternaria Leaf Spot': DiseaseData(
      name: 'Alternaria Leaf Spot',
      imagePath: 'assets/diseases/alternaria_leaf_spot.jpg',
      preventionStrategies: ['Remove infected debris', 'Improve air circulation'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Humid weather', 'Dense foliage'],
      fungicides: ['Dithane (Mancozeb)', 'Manzate (Mancozeb)'],
    ),
    'Alternaria Stem Canker': DiseaseData(
      name: 'Alternaria Stem Canker',
      imagePath: 'assets/diseases/alternaria_stem_canker.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Iprodione',
      possibleCauses: ['Warm, wet conditions', 'Mechanical injury'],
      fungicides: ['Rovral (Iprodione)', 'Chipco (Iprodione)'],
    ),
    'Angular Leaf Spot': DiseaseData(
      name: 'Angular Leaf Spot',
      imagePath: 'assets/diseases/angular_leaf_spot.jpg',
      preventionStrategies: ['Use certified seeds', 'Avoid overhead irrigation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Infected seeds'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Anthracnose': DiseaseData(
      name: 'Anthracnose',
      imagePath: 'assets/diseases/anthracnose.jpg',
      preventionStrategies: ['Use certified seeds', 'Crop rotation'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Wet conditions', 'Infected plant debris'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Anthracnose Leaf Blight': DiseaseData(
      name: 'Anthracnose Leaf Blight',
      imagePath: 'assets/diseases/anthracnose_leaf_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Residue management'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Crop residue'],
      fungicides: ['Quadris (Azoxystrobin)', 'Heritage (Azoxystrobin)'],
    ),
    'Aspergillus Ear Rot': DiseaseData(
      name: 'Aspergillus Ear Rot',
      imagePath: 'assets/diseases/aspergillus_ear_rot.jpg',
      preventionStrategies: ['Proper drying of grain', 'Avoid mechanical damage'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Warm, dry conditions', 'Insect damage'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Ascochyta Blight': DiseaseData(
      name: 'Ascochyta Blight',
      imagePath: 'assets/diseases/ascochyta_blight.jpg',
      preventionStrategies: ['Use resistant varieties', 'Crop rotation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Cool, wet weather', 'Infected seeds'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Aster Yellows': DiseaseData(
      name: 'Aster Yellows',
      imagePath: 'assets/diseases/aster_yellows.jpg',
      preventionStrategies: ['Control leafhoppers', 'Remove weeds'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Leafhopper transmission', 'Weed hosts'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),

    // B
    'Bacterial Canker': DiseaseData(
      name: 'Bacterial Canker',
      imagePath: 'assets/diseases/bacterial_canker.jpg',
      preventionStrategies: ['Use clean seeds', 'Avoid pruning in wet conditions'],
      activeAgent: 'Copper sulfate',
      possibleCauses: ['Wet weather', 'Mechanical injury'],
      fungicides: ['Bordeaux mixture', 'Coppercide (Copper sulfate)'],
    ),
    'Bacterial Leaf Blight': DiseaseData(
      name: 'Bacterial Leaf Blight',
      imagePath: 'assets/diseases/bacterial_leaf_blight.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid overhead irrigation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Warm, wet conditions', 'Infected seeds'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Bacterial Leaf Streak': DiseaseData(
      name: 'Bacterial Leaf Streak',
      imagePath: 'assets/diseases/bacterial_leaf_streak.jpg',
      preventionStrategies: ['Crop rotation', 'Use clean seeds'],
      activeAgent: 'Copper oxychloride',
      possibleCauses: ['Wet conditions', 'Infected residue'],
      fungicides: ['Cuprofix (Copper oxychloride)', 'Nordox (Copper oxychloride)'],
    ),
    'Bacterial Soft Rot': DiseaseData(
      name: 'Bacterial Soft Rot',
      imagePath: 'assets/diseases/bacterial_soft_rot.jpg',
      preventionStrategies: ['Avoid waterlogging', 'Proper storage'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Mechanical injury'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Bacterial Spot': DiseaseData(
      name: 'Bacterial Spot',
      imagePath: 'assets/diseases/bacterial_spot.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid overhead irrigation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Warm, wet weather', 'Infected seeds'],
      fungicides: ['Kocide (Copper hydroxide)', 'Coppercide (Copper sulfate)'],
    ),
    'Bacterial Stalk Rot': DiseaseData(
      name: 'Bacterial Stalk Rot',
      imagePath: 'assets/diseases/bacterial_stalk_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Avoid injury to plants'],
      activeAgent: 'Copper oxychloride',
      possibleCauses: ['Wet conditions', 'Mechanical damage'],
      fungicides: ['Cuprofix (Copper oxychloride)', 'Nordox (Copper oxychloride)'],
    ),
    'Bacterial Wilt': DiseaseData(
      name: 'Bacterial Wilt',
      imagePath: 'assets/diseases/bacterial_wilt.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Streptomycin',
      possibleCauses: ['Soil-borne bacteria', 'Warm, wet conditions'],
      fungicides: ['Agri-Mycin (Streptomycin)', 'Strepto (Streptomycin)'],
    ),
    'Bakanae Disease': DiseaseData(
      name: 'Bakanae Disease',
      imagePath: 'assets/diseases/bakanae_disease.jpg',
      preventionStrategies: ['Use treated seeds', 'Proper water management'],
      activeAgent: 'Prochloraz',
      possibleCauses: ['Infected seeds', 'Warm conditions'],
      fungicides: ['Sportak (Prochloraz)', 'Prelude (Prochloraz)'],
    ),
    'Barley Yellow Dwarf Virus': DiseaseData(
      name: 'Barley Yellow Dwarf Virus',
      imagePath: 'assets/diseases/barley_yellow_dwarf_virus.jpg',
      preventionStrategies: ['Control aphids', 'Plant resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Early planting'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Bean Common Mosaic Virus': DiseaseData(
      name: 'Bean Common Mosaic Virus',
      imagePath: 'assets/diseases/bean_common_mosaic_virus.jpg',
      preventionStrategies: ['Use resistant varieties', 'Control aphids'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected seeds'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Bean Golden Yellow Mosaic Virus': DiseaseData(
      name: 'Bean Golden Yellow Mosaic Virus',
      imagePath: 'assets/diseases/bean_golden_yellow_mosaic_virus.jpg',
      preventionStrategies: ['Control whiteflies', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Whitefly transmission', 'Warm weather'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Bean Rust': DiseaseData(
      name: 'Bean Rust',
      imagePath: 'assets/diseases/bean_rust.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Humid conditions', 'Rust spores'],
      fungicides: ['Folicur (Tebuconazole)', 'Tilt (Propiconazole)'],
    ),
    'Black Dot': DiseaseData(
      name: 'Black Dot',
      imagePath: 'assets/diseases/black_dot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid water stress'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Wet conditions', 'Soil-borne fungi'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Black Leg': DiseaseData(
      name: 'Black Leg',
      imagePath: 'assets/diseases/black_leg.jpg',
      preventionStrategies: ['Use certified seed', 'Crop rotation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Infected tubers'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Black Rot': DiseaseData(
      name: 'Black Rot',
      imagePath: 'assets/diseases/black_rot.jpg',
      preventionStrategies: ['Crop rotation', 'Use clean seeds'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet foliage', 'Infected seeds'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Blackleg': DiseaseData(
      name: 'Blackleg',
      imagePath: 'assets/diseases/blackleg.jpg',
      preventionStrategies: ['Use certified tubers', 'Avoid wet conditions'],
      activeAgent: 'Copper oxychloride',
      possibleCauses: ['Wet soil', 'Infected tubers'],
      fungicides: ['Cuprofix (Copper oxychloride)', 'Nordox (Copper oxychloride)'],
    ),
    'Brown Rot': DiseaseData(
      name: 'Brown Rot',
      imagePath: 'assets/diseases/brown_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Avoid injury'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Mechanical damage'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Brown Spot': DiseaseData(
      name: 'Brown Spot',
      imagePath: 'assets/diseases/brown_spot.jpg',
      preventionStrategies: ['Balanced fertilization', 'Proper water management'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Nutrient deficiency', 'Humid conditions'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),

    // C
    'Carrot Mosaic Virus': DiseaseData(
      name: 'Carrot Mosaic Virus',
      imagePath: 'assets/diseases/carrot_mosaic_virus.jpg',
      preventionStrategies: ['Control aphids', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected plants'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Cassava Anthracnose Disease': DiseaseData(
      name: 'Cassava Anthracnose Disease',
      imagePath: 'assets/diseases/cassava_anthracnose_disease.jpg',
      preventionStrategies: ['Use healthy cuttings', 'Crop rotation'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Wet conditions', 'Infected plant material'],
      fungicides: ['Dithane (Mancozeb)', 'Manzate (Mancozeb)'],
    ),
    'Cassava Brown Streak Disease': DiseaseData(
      name: 'Cassava Brown Streak Disease',
      imagePath: 'assets/diseases/cassava_brown_streak_disease.jpg',
      preventionStrategies: ['Use resistant varieties', 'Remove infected plants'],
      activeAgent: 'None (cultural control)',
      possibleCauses: ['Whitefly transmission', 'Infected cuttings'],
      fungicides: ['No fungicide; manage vectors and sanitation'],
    ),
    'Cassava Mosaic Disease': DiseaseData(
      name: 'Cassava Mosaic Disease',
      imagePath: 'assets/diseases/cassava_mosaic_disease.jpg',
      preventionStrategies: ['Use resistant varieties', 'Remove infected plants'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Whitefly transmission', 'Infected cuttings'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Cercospora Leaf Blight': DiseaseData(
      name: 'Cercospora Leaf Blight',
      imagePath: 'assets/diseases/cercospora_leaf_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Warm, wet conditions', 'Poor sanitation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Cercospora Leaf Spot': DiseaseData(
      name: 'Cercospora Leaf Spot',
      imagePath: 'assets/diseases/cercospora_leaf_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid overhead irrigation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Dense foliage'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Charcoal Rot': DiseaseData(
      name: 'Charcoal Rot',
      imagePath: 'assets/diseases/charcoal_rot.jpg',
      preventionStrategies: ['Avoid drought stress', 'Crop rotation'],
      activeAgent: 'Trichoderma spp. (bio-control)',
      possibleCauses: ['Dry, hot conditions', 'Soil-borne fungi'],
      fungicides: ['No chemical fungicide; use bio-agents'],
    ),
    'Clubroot': DiseaseData(
      name: 'Clubroot',
      imagePath: 'assets/diseases/clubroot.jpg',
      preventionStrategies: ['Raise soil pH', 'Crop rotation'],
      activeAgent: 'Lime (calcium carbonate)',
      possibleCauses: ['Acidic soil', 'Soil-borne pathogen'],
      fungicides: ['No fungicide; use soil amendments'],
    ),
    'Common Bunt': DiseaseData(
      name: 'Common Bunt',
      imagePath: 'assets/diseases/common_bunt.jpg',
      preventionStrategies: ['Use treated seeds', 'Crop rotation'],
      activeAgent: 'Carboxin',
      possibleCauses: ['Infected seeds', 'Cool, wet conditions'],
      fungicides: ['Vitavax (Carboxin)', 'Raxil (Tebuconazole)'],
    ),
    'Common Rust': DiseaseData(
      name: 'Common Rust',
      imagePath: 'assets/diseases/common_rust.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Rust spores'],
      fungicides: ['Quadris (Azoxystrobin)', 'Headline (Pyraclostrobin)'],
    ),
    'Common Scab': DiseaseData(
      name: 'Common Scab',
      imagePath: 'assets/diseases/common_scab.jpg',
      preventionStrategies: ['Maintain soil pH', 'Avoid dry conditions'],
      activeAgent: 'Streptomycin',
      possibleCauses: ['Alkaline soil', 'Dry conditions'],
      fungicides: ['Agri-Mycin (Streptomycin)', 'Strepto (Streptomycin)'],
    ),
    'Common Smut': DiseaseData(
      name: 'Common Smut',
      imagePath: 'assets/diseases/common_smut.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid mechanical injury'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Warm, wet conditions', 'Injured plants'],
      fungicides: ['Folicur (Tebuconazole)', 'Raxil (Tebuconazole)'],
    ),

    // D
    'Damping-Off': DiseaseData(
      name: 'Damping-Off',
      imagePath: 'assets/diseases/damping_off.jpg',
      preventionStrategies: ['Use well-drained soil', 'Seed treatment'],
      activeAgent: 'Metalaxyl',
      possibleCauses: ['Overwatering', 'Soil-borne fungi'],
      fungicides: ['Ridomil (Metalaxyl)', 'Apron (Metalaxyl)'],
    ),
    'Diplodia Ear Rot': DiseaseData(
      name: 'Diplodia Ear Rot',
      imagePath: 'assets/diseases/diplodia_ear_rot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid mechanical damage'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Wet conditions', 'Insect damage'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Downy Mildew': DiseaseData(
      name: 'Downy Mildew',
      imagePath: 'assets/diseases/downy_mildew.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid overhead irrigation'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Cool, wet conditions', 'Dense foliage'],
      fungicides: ['Dithane (Mancozeb)', 'Ridomil Gold (Mancozeb + Metalaxyl)'],
    ),

    // E
    'Early Blight': DiseaseData(
      name: 'Early Blight',
      imagePath: 'assets/diseases/early_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Warm, wet weather', 'Poor sanitation'],
      fungicides: ['Dithane (Mancozeb)', 'Ridomil Gold (Mancozeb + Metalaxyl)'],
    ),
    'Eyespot': DiseaseData(
      name: 'Eyespot',
      imagePath: 'assets/diseases/eyespot.jpg',
      preventionStrategies: ['Crop rotation', 'Residue management'],
      activeAgent: 'Prochloraz',
      possibleCauses: ['Cool, wet conditions', 'Crop residue'],
      fungicides: ['Sportak (Prochloraz)', 'Prelude (Prochloraz)'],
    ),

    // F
    'False Smut': DiseaseData(
      name: 'False Smut',
      imagePath: 'assets/diseases/false_smut.jpg',
      preventionStrategies: ['Use resistant varieties', 'Proper water management'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Humid conditions', 'Late planting'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Fruit Rot': DiseaseData(
      name: 'Fruit Rot',
      imagePath: 'assets/diseases/fruit_rot.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid injury to fruits'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Wet conditions', 'Mechanical damage'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Fusarium Dry Rot': DiseaseData(
      name: 'Fusarium Dry Rot',
      imagePath: 'assets/diseases/fusarium_dry_rot.jpg',
      preventionStrategies: ['Proper storage', 'Avoid injury to tubers'],
      activeAgent: 'Thiophanate-methyl',
      possibleCauses: ['Warm, dry conditions', 'Mechanical damage'],
      fungicides: ['Topsin-M (Thiophanate-methyl)', 'Senator (Thiophanate-methyl)'],
    ),
    'Fusarium Ear Rot': DiseaseData(
      name: 'Fusarium Ear Rot',
      imagePath: 'assets/diseases/fusarium_ear_rot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid insect damage'],
      activeAgent: 'Prothioconazole',
      possibleCauses: ['Warm, wet conditions', 'Insect injury'],
      fungicides: ['Proline (Prothioconazole)', 'Prosaro (Prothioconazole + Tebuconazole)'],
    ),
    'Fusarium Head Blight': DiseaseData(
      name: 'Fusarium Head Blight',
      imagePath: 'assets/diseases/fusarium_head_blight.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Warm, wet conditions', 'Flowering stage'],
      fungicides: ['Folicur (Tebuconazole)', 'Prosaro (Prothioconazole + Tebuconazole)'],
    ),
    'Fusarium Root Rot': DiseaseData(
      name: 'Fusarium Root Rot',
      imagePath: 'assets/diseases/fusarium_root_rot.jpg',
      preventionStrategies: ['Crop rotation', 'Improve drainage'],
      activeAgent: 'Thiophanate-methyl',
      possibleCauses: ['Wet soil', 'Soil-borne fungi'],
      fungicides: ['Topsin-M (Thiophanate-methyl)', 'Senator (Thiophanate-methyl)'],
    ),
    'Fusarium Wilt': DiseaseData(
      name: 'Fusarium Wilt',
      imagePath: 'assets/diseases/fusarium_wilt.jpg',
      preventionStrategies: ['Use resistant varieties', 'Crop rotation'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Warm soil', 'Soil-borne fungi'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),
    'Fusarium Yellows': DiseaseData(
      name: 'Fusarium Yellows',
      imagePath: 'assets/diseases/fusarium_yellows.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Warm conditions', 'Soil-borne pathogen'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),

    // G
    'Gibberella Ear Rot': DiseaseData(
      name: 'Gibberella Ear Rot',
      imagePath: 'assets/diseases/gibberella_ear_rot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid insect damage'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Cool, wet conditions', 'Insect injury'],
      fungicides: ['Folicur (Tebuconazole)', 'Prosaro (Prothioconazole + Tebuconazole)'],
    ),
    'Goss’s Wilt': DiseaseData(
      name: 'Goss’s Wilt',
      imagePath: 'assets/diseases/gosss_wilt.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant hybrids'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Warm, wet conditions', 'Mechanical injury'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Grain Discoloration': DiseaseData(
      name: 'Grain Discoloration',
      imagePath: 'assets/diseases/grain_discoloration.jpg',
      preventionStrategies: ['Proper drying', 'Timely harvest'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Wet conditions', 'Fungal infection'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Gray Leaf Spot': DiseaseData(
      name: 'Gray Leaf Spot',
      imagePath: 'assets/diseases/gray_leaf_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Residue management'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Crop residue'],
      fungicides: ['Quadris (Azoxystrobin)', 'Headline (Pyraclostrobin)'],
    ),
    'Gray Mold (Botrytis)': DiseaseData(
      name: 'Gray Mold (Botrytis)',
      imagePath: 'assets/diseases/gray_mold_botrytis.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid wet foliage'],
      activeAgent: 'Iprodione',
      possibleCauses: ['Cool, wet conditions', 'Dense foliage'],
      fungicides: ['Rovral (Iprodione)', 'Chipco (Iprodione)'],
    ),

    // H
    'Halo Blight': DiseaseData(
      name: 'Halo Blight',
      imagePath: 'assets/diseases/halo_blight.jpg',
      preventionStrategies: ['Use certified seeds', 'Avoid overhead irrigation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Cool, wet conditions', 'Infected seeds'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Head Smut': DiseaseData(
      name: 'Head Smut',
      imagePath: 'assets/diseases/head_smut.jpg',
      preventionStrategies: ['Use resistant varieties', 'Seed treatment'],
      activeAgent: 'Carboxin',
      possibleCauses: ['Infected seeds', 'Warm conditions'],
      fungicides: ['Vitavax (Carboxin)', 'Raxil (Tebuconazole)'],
    ),

    // K
    'Karnal Bunt': DiseaseData(
      name: 'Karnal Bunt',
      imagePath: 'assets/diseases/karnal_bunt.jpg',
      preventionStrategies: ['Use treated seeds', 'Avoid late irrigation'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Cool, wet conditions', 'Infected seeds'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),

    // L
    'Late Blight': DiseaseData(
      name: 'Late Blight',
      imagePath: 'assets/diseases/late_blight.jpg',
      preventionStrategies: ['Remove volunteer plants', 'Apply fungicides early'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Cool, wet weather', 'Infected tubers'],
      fungicides: ['Dithane (Mancozeb)', 'Ridomil Gold (Mancozeb + Metalaxyl)'],
    ),
    'Leaf Blight': DiseaseData(
      name: 'Leaf Blight',
      imagePath: 'assets/diseases/leaf_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Wet conditions', 'Poor sanitation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Leaf Rust': DiseaseData(
      name: 'Leaf Rust',
      imagePath: 'assets/diseases/leaf_rust.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Warm, moist conditions', 'Rust spores'],
      fungicides: ['Folicur (Tebuconazole)', 'Tilt (Propiconazole)'],
    ),
    'Leaf Scald': DiseaseData(
      name: 'Leaf Scald',
      imagePath: 'assets/diseases/leaf_scald.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid overhead irrigation'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Infected plant material'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Leaf Smut': DiseaseData(
      name: 'Leaf Smut',
      imagePath: 'assets/diseases/leaf_smut.jpg',
      preventionStrategies: ['Use resistant varieties', 'Proper water management'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Humid conditions', 'Infected seeds'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Loose Smut': DiseaseData(
      name: 'Loose Smut',
      imagePath: 'assets/diseases/loose_smut.jpg',
      preventionStrategies: ['Use treated seeds', 'Crop rotation'],
      activeAgent: 'Carboxin',
      possibleCauses: ['Infected seeds', 'Cool, wet conditions'],
      fungicides: ['Vitavax (Carboxin)', 'Raxil (Tebuconazole)'],
    ),

    // M
    'Maize Dwarf Mosaic Virus': DiseaseData(
      name: 'Maize Dwarf Mosaic Virus',
      imagePath: 'assets/diseases/maize_dwarf_mosaic_virus.jpg',
      preventionStrategies: ['Control aphids', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected seeds'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Maize Lethal Necrosis': DiseaseData(
      name: 'Maize Lethal Necrosis',
      imagePath: 'assets/diseases/maize_lethal_necrosis.jpg',
      preventionStrategies: ['Use resistant varieties', 'Control insect vectors'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Virus transmission by aphids/thrips', 'Infected seeds'],
      fungicides: ['No direct fungicide; manage vectors with insecticides'],
    ),
    'Maize Streak Virus': DiseaseData(
      name: 'Maize Streak Virus',
      imagePath: 'assets/diseases/maize_streak_virus.jpg',
      preventionStrategies: ['Control leafhoppers', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Leafhopper transmission', 'Warm conditions'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),

    // N
    'Northern Corn Leaf Blight': DiseaseData(
      name: 'Northern Corn Leaf Blight',
      imagePath: 'assets/diseases/northern_corn_leaf_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant hybrids'],
      activeAgent: 'Pyraclostrobin',
      possibleCauses: ['Cool, wet conditions', 'Crop residue'],
      fungicides: ['Headline (Pyraclostrobin)', 'Quadris (Azoxystrobin)'],
    ),

    // P
    'Pineapple Disease': DiseaseData(
      name: 'Pineapple Disease',
      imagePath: 'assets/diseases/pineapple_disease.jpg',
      preventionStrategies: ['Use disease-free setts', 'Proper curing'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Wet conditions', 'Infected setts'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),
    'Pink Rot': DiseaseData(
      name: 'Pink Rot',
      imagePath: 'assets/diseases/pink_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Avoid overwatering'],
      activeAgent: 'Mefenoxam',
      possibleCauses: ['Wet soil', 'Soil-borne fungi'],
      fungicides: ['Ridomil Gold (Mefenoxam)', 'Ultra Flourish (Mefenoxam)'],
    ),
    'Pokkah Boeng': DiseaseData(
      name: 'Pokkah Boeng',
      imagePath: 'assets/diseases/pokkah_boeng.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid stress'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Humid conditions', 'Nutrient imbalance'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),
    'Post-Harvest Fungal Rot': DiseaseData(
      name: 'Post-Harvest Fungal Rot',
      imagePath: 'assets/diseases/post_harvest_fungal_rot.jpg',
      preventionStrategies: ['Proper drying', 'Cool storage'],
      activeAgent: 'Thiabendazole',
      possibleCauses: ['High humidity', 'Mechanical damage'],
      fungicides: ['Mertect (Thiabendazole)', 'Shield (Thiabendazole)'],
    ),
    'Post-Harvest Mycotoxins (Aflatoxins, Fumonisins)': DiseaseData(
      name: 'Post-Harvest Mycotoxins (Aflatoxins, Fumonisins)',
      imagePath: 'assets/diseases/post_harvest_mycotoxins.jpg',
      preventionStrategies: ['Proper drying', 'Cool, dry storage'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Warm, humid conditions', 'Insect damage'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Post-Harvest Rot': DiseaseData(
      name: 'Post-Harvest Rot',
      imagePath: 'assets/diseases/post_harvest_rot.jpg',
      preventionStrategies: ['Proper storage', 'Avoid injury'],
      activeAgent: 'Thiabendazole',
      possibleCauses: ['High humidity', 'Mechanical damage'],
      fungicides: ['Mertect (Thiabendazole)', 'Shield (Thiabendazole)'],
    ),
    'Potato Leafroll Virus': DiseaseData(
      name: 'Potato Leafroll Virus',
      imagePath: 'assets/diseases/potato_leafroll_virus.jpg',
      preventionStrategies: ['Control aphids', 'Use certified tubers'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected tubers'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Potato Mop-Top Virus': DiseaseData(
      name: 'Potato Mop-Top Virus',
      imagePath: 'assets/diseases/potato_mop_top_virus.jpg',
      preventionStrategies: ['Use resistant varieties', 'Control soil vectors'],
      activeAgent: 'None (cultural control)',
      possibleCauses: ['Soil-borne fungi', 'Infected tubers'],
      fungicides: ['No fungicide; manage soil health'],
    ),
    'Potato Virus Y': DiseaseData(
      name: 'Potato Virus Y',
      imagePath: 'assets/diseases/potato_virus_y.jpg',
      preventionStrategies: ['Control aphids', 'Use certified tubers'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected tubers'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Powdery Mildew': DiseaseData(
      name: 'Powdery Mildew',
      imagePath: 'assets/diseases/powdery_mildew.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid overhead irrigation'],
      activeAgent: 'Sulfur',
      possibleCauses: ['Warm, dry conditions', 'Dense foliage'],
      fungicides: ['Microthiol (Sulfur)', 'Kumulus (Sulfur)'],
    ),
    'Powdery Scab': DiseaseData(
      name: 'Powdery Scab',
      imagePath: 'assets/diseases/powdery_scab.jpg',
      preventionStrategies: ['Use certified tubers', 'Avoid wet soils'],
      activeAgent: 'Fluazinam',
      possibleCauses: ['Cool, wet conditions', 'Soil-borne pathogen'],
      fungicides: ['Omega (Fluazinam)', 'Shirlan (Fluazinam)'],
    ),
    'Pythium Root Rot': DiseaseData(
      name: 'Pythium Root Rot',
      imagePath: 'assets/diseases/pythium_root_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Seed treatment'],
      activeAgent: 'Metalaxyl',
      possibleCauses: ['Wet soil', 'Soil-borne fungi'],
      fungicides: ['Ridomil (Metalaxyl)', 'Apron (Metalaxyl)'],
    ),

    // R
    'Ratoon Stunting Disease': DiseaseData(
      name: 'Ratoon Stunting Disease',
      imagePath: 'assets/diseases/ratoon_stunting_disease.jpg',
      preventionStrategies: ['Use disease-free setts', 'Crop rotation'],
      activeAgent: 'None (cultural control)',
      possibleCauses: ['Soil-borne bacteria', 'Poor management'],
      fungicides: ['No fungicide; improve sanitation'],
    ),
    'Red Rot': DiseaseData(
      name: 'Red Rot',
      imagePath: 'assets/diseases/red_rot.jpg',
      preventionStrategies: ['Use disease-free setts', 'Crop rotation'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Injured cane', 'Humid conditions'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),
    'Rhizoctonia Black Scurf': DiseaseData(
      name: 'Rhizoctonia Black Scurf',
      imagePath: 'assets/diseases/rhizoctonia_black_scurf.jpg',
      preventionStrategies: ['Crop rotation', 'Seed treatment'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Cool, wet soil', 'Soil-borne fungi'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Rhizoctonia Root Rot': DiseaseData(
      name: 'Rhizoctonia Root Rot',
      imagePath: 'assets/diseases/rhizoctonia_root_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Crop rotation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Wet soil', 'Soil-borne fungi'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Rice Blast': DiseaseData(
      name: 'Rice Blast',
      imagePath: 'assets/diseases/rice_blast.jpg',
      preventionStrategies: ['Use resistant varieties', 'Avoid excessive nitrogen'],
      activeAgent: 'Tricyclazole',
      possibleCauses: ['Humid conditions', 'Poor water management'],
      fungicides: ['Beam (Tricyclazole)', 'Fuji-One (Isoprothiolane)'],
    ),
    'Ring Rot': DiseaseData(
      name: 'Ring Rot',
      imagePath: 'assets/diseases/ring_rot.jpg',
      preventionStrategies: ['Use certified tubers', 'Sanitize equipment'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Infected tubers', 'Mechanical spread'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Ring Spot': DiseaseData(
      name: 'Ring Spot',
      imagePath: 'assets/diseases/ring_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Wet conditions', 'Poor sanitation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Root Knot Nematodes': DiseaseData(
      name: 'Root Knot Nematodes',
      imagePath: 'assets/diseases/root_knot_nematodes.jpg',
      preventionStrategies: ['Crop rotation', 'Soil solarization'],
      activeAgent: 'Oxamyl',
      possibleCauses: ['Infested soil', 'Warm conditions'],
      fungicides: ['Vydate (Oxamyl)', 'Nemacur (Fenamiphos)'],
    ),
    'Root Rot': DiseaseData(
      name: 'Root Rot',
      imagePath: 'assets/diseases/root_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Avoid overwatering'],
      activeAgent: 'Metalaxyl',
      possibleCauses: ['Wet soil', 'Soil-borne fungi'],
      fungicides: ['Ridomil (Metalaxyl)', 'Apron (Metalaxyl)'],
    ),
    'Rust': DiseaseData(
      name: 'Rust',
      imagePath: 'assets/diseases/rust.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Humid conditions', 'Rust spores'],
      fungicides: ['Folicur (Tebuconazole)', 'Tilt (Propiconazole)'],
    ),

    // S
    'Sclerotinia Stem Rot (White Mold)': DiseaseData(
      name: 'Sclerotinia Stem Rot (White Mold)',
      imagePath: 'assets/diseases/sclerotinia_stem_rot.jpg',
      preventionStrategies: ['Improve air circulation', 'Crop rotation'],
      activeAgent: 'Boscalid',
      possibleCauses: ['Cool, wet conditions', 'Dense canopy'],
      fungicides: ['Endura (Boscalid)', 'Lance (Boscalid)'],
    ),
    'Sclerotinia White Mold': DiseaseData(
      name: 'Sclerotinia White Mold',
      imagePath: 'assets/diseases/sclerotinia_white_mold.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid dense planting'],
      activeAgent: 'Boscalid',
      possibleCauses: ['Cool, wet conditions', 'Soil-borne fungi'],
      fungicides: ['Endura (Boscalid)', 'Lance (Boscalid)'],
    ),
    'Septoria Leaf Blotch': DiseaseData(
      name: 'Septoria Leaf Blotch',
      imagePath: 'assets/diseases/septoria_leaf_blotch.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Wet conditions', 'Crop residue'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Septoria Leaf Spot': DiseaseData(
      name: 'Septoria Leaf Spot',
      imagePath: 'assets/diseases/septoria_leaf_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Avoid overhead irrigation'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Warm, wet conditions', 'Poor sanitation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'Sheath Blight': DiseaseData(
      name: 'Sheath Blight',
      imagePath: 'assets/diseases/sheath_blight.jpg',
      preventionStrategies: ['Avoid excessive nitrogen', 'Improve air circulation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Dense planting'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Sheath Rot': DiseaseData(
      name: 'Sheath Rot',
      imagePath: 'assets/diseases/sheath_rot.jpg',
      preventionStrategies: ['Proper water management', 'Use resistant varieties'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Wet conditions', 'Infected residue'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Silver Scurf': DiseaseData(
      name: 'Silver Scurf',
      imagePath: 'assets/diseases/silver_scurf.jpg',
      preventionStrategies: ['Proper storage', 'Seed treatment'],
      activeAgent: 'Thiabendazole',
      possibleCauses: ['High humidity', 'Infected tubers'],
      fungicides: ['Mertect (Thiabendazole)', 'Shield (Thiabendazole)'],
    ),
    'Smut': DiseaseData(
      name: 'Smut',
      imagePath: 'assets/diseases/smut.jpg',
      preventionStrategies: ['Use resistant varieties', 'Seed treatment'],
      activeAgent: 'Carboxin',
      possibleCauses: ['Infected seeds', 'Warm conditions'],
      fungicides: ['Vitavax (Carboxin)', 'Raxil (Tebuconazole)'],
    ),
    'Snow Mold': DiseaseData(
      name: 'Snow Mold',
      imagePath: 'assets/diseases/snow_mold.jpg',
      preventionStrategies: ['Avoid late fertilization', 'Improve drainage'],
      activeAgent: 'Iprodione',
      possibleCauses: ['Snow cover', 'Cold, wet conditions'],
      fungicides: ['Rovral (Iprodione)', 'Chipco (Iprodione)'],
    ),
    'Soft Rot': DiseaseData(
      name: 'Soft Rot',
      imagePath: 'assets/diseases/soft_rot.jpg',
      preventionStrategies: ['Avoid waterlogging', 'Proper storage'],
      activeAgent: 'Copper hydroxide',
      possibleCauses: ['Wet conditions', 'Mechanical injury'],
      fungicides: ['Kocide (Copper hydroxide)', 'Champ (Copper hydroxide)'],
    ),
    'Southern Blight': DiseaseData(
      name: 'Southern Blight',
      imagePath: 'assets/diseases/southern_blight.jpg',
      preventionStrategies: ['Crop rotation', 'Soil solarization'],
      activeAgent: 'Penthiopyrad',
      possibleCauses: ['Warm, moist conditions', 'Soil-borne fungi'],
      fungicides: ['Fontelis (Penthiopyrad)', 'Vertisan (Penthiopyrad)'],
    ),
    'Southern Corn Leaf Blight': DiseaseData(
      name: 'Southern Corn Leaf Blight',
      imagePath: 'assets/diseases/southern_corn_leaf_blight.jpg',
      preventionStrategies: ['Use resistant hybrids', 'Crop rotation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Warm, wet conditions', 'Crop residue'],
      fungicides: ['Quadris (Azoxystrobin)', 'Headline (Pyraclostrobin)'],
    ),
    'Stem Rot': DiseaseData(
      name: 'Stem Rot',
      imagePath: 'assets/diseases/stem_rot.jpg',
      preventionStrategies: ['Improve drainage', 'Crop rotation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Wet conditions', 'Soil-borne fungi'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Stem Rust': DiseaseData(
      name: 'Stem Rust',
      imagePath: 'assets/diseases/stem_rust.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Warm, moist conditions', 'Rust spores'],
      fungicides: ['Folicur (Tebuconazole)', 'Tilt (Propiconazole)'],
    ),
    'Stewart’s Wilt': DiseaseData(
      name: 'Stewart’s Wilt',
      imagePath: 'assets/diseases/stewarts_wilt.jpg',
      preventionStrategies: ['Control flea beetles', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Flea beetle transmission', 'Warm conditions'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Storage Rot': DiseaseData(
      name: 'Storage Rot',
      imagePath: 'assets/diseases/storage_rot.jpg',
      preventionStrategies: ['Proper drying', 'Cool storage'],
      activeAgent: 'Thiabendazole',
      possibleCauses: ['High humidity', 'Mechanical damage'],
      fungicides: ['Mertect (Thiabendazole)', 'Shield (Thiabendazole)'],
    ),
    'Stripe Rust': DiseaseData(
      name: 'Stripe Rust',
      imagePath: 'assets/diseases/stripe_rust.jpg',
      preventionStrategies: ['Use resistant varieties', 'Timely fungicide application'],
      activeAgent: 'Tebuconazole',
      possibleCauses: ['Cool, moist conditions', 'Rust spores'],
      fungicides: ['Folicur (Tebuconazole)', 'Tilt (Propiconazole)'],
    ),
    'Sugarcane Mosaic Virus': DiseaseData(
      name: 'Sugarcane Mosaic Virus',
      imagePath: 'assets/diseases/sugarcane_mosaic_virus.jpg',
      preventionStrategies: ['Control aphids', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Infected setts'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),

    // T
    'Take-All Disease': DiseaseData(
      name: 'Take-All Disease',
      imagePath: 'assets/diseases/take_all_disease.jpg',
      preventionStrategies: ['Crop rotation', 'Maintain soil health'],
      activeAgent: 'Silthiopham',
      possibleCauses: ['Continuous cropping', 'Soil-borne fungi'],
      fungicides: ['Monceren (Silthiopham)', 'Latitude (Silthiopham)'],
    ),
    'Tan Spot': DiseaseData(
      name: 'Tan Spot',
      imagePath: 'assets/diseases/tan_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Residue management'],
      activeAgent: 'Propiconazole',
      possibleCauses: ['Wet conditions', 'Crop residue'],
      fungicides: ['Tilt (Propiconazole)', 'PropiMax (Propiconazole)'],
    ),
    'Tar Spot': DiseaseData(
      name: 'Tar Spot',
      imagePath: 'assets/diseases/tar_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant hybrids'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Cool, wet conditions', 'Crop residue'],
      fungicides: ['Quadris (Azoxystrobin)', 'Headline (Pyraclostrobin)'],
    ),
    'Tomato Mosaic Virus': DiseaseData(
      name: 'Tomato Mosaic Virus',
      imagePath: 'assets/diseases/tomato_mosaic_virus.jpg',
      preventionStrategies: ['Use resistant varieties', 'Sanitize tools'],
      activeAgent: 'None (cultural control)',
      possibleCauses: ['Mechanical transmission', 'Infected seeds'],
      fungicides: ['No fungicide; improve sanitation'],
    ),
    'Tomato Spotted Wilt Virus': DiseaseData(
      name: 'Tomato Spotted Wilt Virus',
      imagePath: 'assets/diseases/tomato_spotted_wilt_virus.jpg',
      preventionStrategies: ['Control thrips', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Thrips transmission', 'Infected plants'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Tomato Yellow Leaf Curl Virus': DiseaseData(
      name: 'Tomato Yellow Leaf Curl Virus',
      imagePath: 'assets/diseases/tomato_yellow_leaf_curl_virus.jpg',
      preventionStrategies: ['Control whiteflies', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Whitefly transmission', 'Warm conditions'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'Tungro Disease': DiseaseData(
      name: 'Tungro Disease',
      imagePath: 'assets/diseases/tungro_disease.jpg',
      preventionStrategies: ['Control leafhoppers', 'Use resistant varieties'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Leafhopper transmission', 'Infected plants'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),

    // U
    'Ufra Disease': DiseaseData(
      name: 'Ufra Disease',
      imagePath: 'assets/diseases/ufra_disease.jpg',
      preventionStrategies: ['Crop rotation', 'Control nematodes'],
      activeAgent: 'Oxamyl',
      possibleCauses: ['Nematode infestation', 'Wet conditions'],
      fungicides: ['Vydate (Oxamyl)', 'Nemacur (Fenamiphos)'],
    ),

    // V
    'Verticillium Wilt': DiseaseData(
      name: 'Verticillium Wilt',
      imagePath: 'assets/diseases/verticillium_wilt.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Soil-borne fungi', 'Warm conditions'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),

    // W
    'Web Blight': DiseaseData(
      name: 'Web Blight',
      imagePath: 'assets/diseases/web_blight.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid overhead irrigation'],
      activeAgent: 'Azoxystrobin',
      possibleCauses: ['Humid conditions', 'Dense foliage'],
      fungicides: ['Quadris (Azoxystrobin)', 'Amistar (Azoxystrobin)'],
    ),
    'Wheat Streak Mosaic Virus': DiseaseData(
      name: 'Wheat Streak Mosaic Virus',
      imagePath: 'assets/diseases/wheat_streak_mosaic_virus.jpg',
      preventionStrategies: ['Control wheat curl mites', 'Avoid late planting'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Mite transmission', 'Infected plants'],
      fungicides: ['No fungicide; manage vectors with insecticides'],
    ),
    'White Leaf Spot': DiseaseData(
      name: 'White Leaf Spot',
      imagePath: 'assets/diseases/white_leaf_spot.jpg',
      preventionStrategies: ['Crop rotation', 'Remove infected debris'],
      activeAgent: 'Chlorothalonil',
      possibleCauses: ['Wet conditions', 'Poor sanitation'],
      fungicides: ['Daconil (Chlorothalonil)', 'Bravo (Chlorothalonil)'],
    ),
    'White Rust': DiseaseData(
      name: 'White Rust',
      imagePath: 'assets/diseases/white_rust.jpg',
      preventionStrategies: ['Improve air circulation', 'Avoid overhead irrigation'],
      activeAgent: 'Mancozeb',
      possibleCauses: ['Cool, wet conditions', 'Dense foliage'],
      fungicides: ['Dithane (Mancozeb)', 'Manzate (Mancozeb)'],
    ),
    'White Tip Disease': DiseaseData(
      name: 'White Tip Disease',
      imagePath: 'assets/diseases/white_tip_disease.jpg',
      preventionStrategies: ['Control nematodes', 'Use resistant varieties'],
      activeAgent: 'Oxamyl',
      possibleCauses: ['Nematode infestation', 'Wet conditions'],
      fungicides: ['Vydate (Oxamyl)', 'Nemacur (Fenamiphos)'],
    ),
    'Wilt Disease': DiseaseData(
      name: 'Wilt Disease',
      imagePath: 'assets/diseases/wilt_disease.jpg',
      preventionStrategies: ['Crop rotation', 'Use resistant varieties'],
      activeAgent: 'Carbendazim',
      possibleCauses: ['Soil-borne fungi', 'Warm conditions'],
      fungicides: ['Bavistin (Carbendazim)', 'Benlate (Benomyl)'],
    ),

    // Y
    'Yellow Leaf Disease': DiseaseData(
      name: 'Yellow Leaf Disease',
      imagePath: 'assets/diseases/yellow_leaf_disease.jpg',
      preventionStrategies: ['Control aphids', 'Maintain plant health'],
      activeAgent: 'Imidacloprid (for vectors)',
      possibleCauses: ['Aphid transmission', 'Nutrient deficiency'],
      fungicides: ['No fungicide; manage vectors and nutrition'],
    ),
  };
}

class DiseaseIntervention {
  final String? id;
  final String diseaseName;
  final String cropType;
  final String cropStage;
  final String intervention;
  final double? dosage;
  final String? unit;
  final double? area;
  final String areaUnit;
  final Timestamp timestamp;
  final String userId;

  DiseaseIntervention({
    this.id,
    required this.diseaseName,
    required this.cropType,
    required this.cropStage,
    required this.intervention,
    this.dosage,
    this.unit,
    this.area,
    required this.areaUnit,
    required this.timestamp,
    required this.userId,
  });

  Map<String, dynamic> toMap() => {
        'diseaseName': diseaseName,
        'cropType': cropType,
        'cropStage': cropStage,
        'intervention': intervention,
        'dosage': dosage,
        'unit': unit,
        'area': area,
        'areaUnit': areaUnit,
        'timestamp': timestamp,
        'userId': userId,
      };

  factory DiseaseIntervention.fromMap(Map<String, dynamic> map, String id) => DiseaseIntervention(
        id: id,
        diseaseName: map['diseaseName'] as String,
        cropType: map['cropType'] as String,
        cropStage: map['cropStage'] as String,
        intervention: map['intervention'] as String,
        dosage: map['dosage'] as double?,
        unit: map['unit'] as String?,
        area: map['area'] as double?,
        areaUnit: map['areaUnit'] as String,
        timestamp: map['timestamp'] as Timestamp,
        userId: map['userId'] as String,
      );

  DiseaseIntervention copyWith({
    String? id,
    String? diseaseName,
    String? cropType,
    String? cropStage,
    String? intervention,
    double? dosage,
    String? unit,
    double? area,
    String? areaUnit,
    Timestamp? timestamp,
    String? userId,
  }) => DiseaseIntervention(
        id: id ?? this.id,
        diseaseName: diseaseName ?? this.diseaseName,
        cropType: cropType ?? this.cropType,
        cropStage: cropStage ?? this.cropStage,
        intervention: intervention ?? this.intervention,
        dosage: dosage ?? this.dosage,
        unit: unit ?? this.unit,
        area: area ?? this.area,
        areaUnit: areaUnit ?? this.areaUnit,
        timestamp: timestamp ?? this.timestamp,
        userId: userId ?? this.userId,
      );
}