// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBGxVcKrjjC-ZpmgzLltUOlpe8cUciC8',
    appId: '1:865770087354:web:fe0785f373c312f0167383',
    messagingSenderId: '865770087354',
    projectId: 'kilimomkononi-e1031',
    authDomain: 'kilimomkononi-e1031.firebaseapp.com',
    storageBucket: 'kilimomkononi-e1031.firebasestorage.app',
    measurementId: 'G-71NGFMK8PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnNIu1fqF1ySSwT4Y-ko9OCP8VjK64gKs',
    appId: '1:865770087354:android:36439826cd3080de167383',
    messagingSenderId: '865770087354',
    projectId: 'kilimomkononi-e1031',
    storageBucket: 'kilimomkononi-e1031.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvD-E5xewsq06kfj3fh8ARukb7c9us51U',
    appId: '1:865770087354:ios:c0fe052ea52649e2167383',
    messagingSenderId: '865770087354',
    projectId: 'kilimomkononi-e1031',
    storageBucket: 'kilimomkononi-e1031.firebasestorage.app',
    iosBundleId: 'com.example.kilimomkononi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvD-E5xewsq06kfj3fh8ARukb7c9us51U',
    appId: '1:865770087354:ios:c0fe052ea52649e2167383',
    messagingSenderId: '865770087354',
    projectId: 'kilimomkononi-e1031',
    storageBucket: 'kilimomkononi-e1031.firebasestorage.app',
    iosBundleId: 'com.example.kilimomkononi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKBGxVcKrjjC-ZpmgzLltUOlpe8cUciC8',
    appId: '1:865770087354:web:2b0337bcea35970d167383',
    messagingSenderId: '865770087354',
    projectId: 'kilimomkononi-e1031',
    authDomain: 'kilimomkononi-e1031.firebaseapp.com',
    storageBucket: 'kilimomkononi-e1031.firebasestorage.app',
    measurementId: 'G-SBJ75M0TC0',
  );
}
